import { Candle, Signal } from "./indicators";
import * as smc from "./strategies/smc";
import * as ind from "./strategies/indicators";
import * as meme from "./strategies/memecoin";
import * as scalp from "./strategies/scalping";
import * as mrev from "./strategies/meanrev";
import * as trend from "./strategies/trend";
import * as brk from "./strategies/breakout";
import * as pat from "./strategies/patterns";

export type Category = "smc" | "indicators" | "memecoin" | "scalping" | "meanrev" | "trend" | "breakout" | "patterns";

export interface StrategyMeta {
  id: string;
  slug: string;
  name: string;
  category: Category;
  short: string;
  description: string;
  entry: string;
  exit: string;
  confidence: number;
  langs: ("python" | "typescript" | "pinescript")[];
  run: ((c: Candle[]) => Signal) | null;
  offchainNote?: string;
}

export const STRATEGIES: StrategyMeta[] = [
  // ---------------- SMC (10) ----------------
  { id: "fvg", slug: "fvg", name: "Fair Value Gap (FVG)", category: "smc",
    short: "Liquidity gap in 3 candles, entry on mitigation.",
    description: "An unfilled liquidity gap formed across three consecutive candles. When price moves fast, gaps remain; the market typically returns to fill them (mitigation). Bullish FVG: candle[i-2].high < candle[i].low. Bearish FVG: candle[i-2].low > candle[i].high.",
    entry: "On retracement to the 50% midpoint of the FVG, in the EMA200 trend direction.",
    exit: "SL: opposite end of FVG + 0.5 ATR. TP: tiered 1:2, 1:3, 1:5 RR.",
    confidence: 0.75, langs: ["python", "typescript", "pinescript"], run: smc.fvg },
  { id: "order_block", slug: "order_block", name: "Order Block", category: "smc",
    short: "Last opposite-color candle before a strong move; entry on retest.",
    description: "The last opposite-color candle before a strong impulse move. Represents a zone where institutions accumulated orders. Price often reacts when returning to this zone (retest).",
    entry: "On retest of the OB zone (body midpoint), in trend direction.",
    exit: "SL: other end of OB + 0.5 ATR. TP: 1:2, 1:3, 1:5.",
    confidence: 0.78, langs: ["python", "typescript", "pinescript"], run: smc.orderBlock },
  { id: "liquidity_grab_bos", slug: "liquidity_grab_bos", name: "Liquidity Grab + BOS", category: "smc",
    short: "Stop-hunt followed by Break of Structure.",
    description: "Stop-hunt combined with Break of Structure. Price first sweeps liquidity, then breaks structure in the true direction. One of the highest-confidence SMC patterns.",
    entry: "Market entry on BOS confirmation.",
    exit: "SL: swept wick + 0.3 ATR. TP: 1:2, 1:3, 1:5.",
    confidence: 0.82, langs: ["python", "typescript", "pinescript"], run: smc.liquidityGrabBos },
  { id: "inducement", slug: "inducement", name: "Inducement & Mitigation", category: "smc",
    short: "Fake breakout traps retail, then real direction starts.",
    description: "Inducement = a lower-timeframe fake breakout that pulls in liquidity. Retail traders are trapped, then the real direction begins.",
    entry: "When the previous 3-candle range is broken.",
    exit: "SL: wick high/low + 0.3 ATR. TP: 1:2, 1:3, 1:5.",
    confidence: 0.7, langs: ["python", "typescript", "pinescript"], run: smc.inducement },
  { id: "eq_sweep", slug: "eq_sweep", name: "Equal Highs/Lows Sweep", category: "smc",
    short: "Sweep of liquidity pool at near-equal levels.",
    description: "2+ highs/lows formed at near-identical levels = liquidity pool. Stops accumulate above/below this level. A sweep + reversal triggers entry.",
    entry: "EQH/EQL sweep + reversal candle (tolerance 0.15 ATR).",
    exit: "SL: sweep wick + 0.3 ATR. TP: 1:2, 1:3, 1:5.",
    confidence: 0.76, langs: ["python", "typescript", "pinescript"], run: smc.eqSweep },
  { id: "breaker_block", slug: "breaker_block", name: "Breaker Block", category: "smc",
    short: "Failed order block flips to act as opposite S/R.",
    description: "A failed order block. When an OB is broken, that zone acts as opposite-direction support/resistance. Used in trend reversals.",
    entry: "On retest of the broken OB in opposite direction.",
    exit: "SL: opposite end of breaker + 0.5 ATR. TP: 1:2, 1:3, 1:5.",
    confidence: 0.74, langs: ["python", "typescript", "pinescript"], run: smc.breakerBlock },
  { id: "ote", slug: "ote", name: "Optimal Trade Entry (OTE)", category: "smc",
    short: "Fibonacci 0.62-0.79 retracement zone.",
    description: "The 0.62-0.79 Fibonacci retracement zone of the last impulse move. Premium = expensive, Discount = cheap. Cornerstone of ICT methodology.",
    entry: "On retracement into 0.62-0.79 fib zone, in trend direction.",
    exit: "SL: impulse low/high + 0.3 ATR. Final TP at impulse peak.",
    confidence: 0.77, langs: ["python", "typescript", "pinescript"], run: smc.ote },
  { id: "choch", slug: "choch", name: "Change of Character (ChoCH)", category: "smc",
    short: "First structural shift in market direction.",
    description: "ChoCH = the first clean reversal signal in trend structure. HH-HL series breaking to LH-LL = bearish ChoCH; LH-LL flipping to HH-HL = bullish ChoCH. Identifies early trend turns.",
    entry: "On structure-break confirmation.",
    exit: "SL: last opposite swing + 0.3 ATR. TP: 1:2, 1:3, 1:5.",
    confidence: 0.79, langs: ["typescript"], run: smc.chochSignal },
  { id: "premium_discount", slug: "premium_discount", name: "Premium / Discount Zones", category: "smc",
    short: "Trade reactions at premium/discount zones of a range.",
    description: "Fib zones of last range. Discount (0-30% position) = cheap, long bias. Premium (70-100%) = expensive, short bias. Equilibrium (30-70%) — wait. SMC's buy/sell zone logic.",
    entry: "Discount + bullish candle = long; Premium + bearish candle = short.",
    exit: "SL: outside range + 0.3 ATR. TP: midpoint → opposite range edge.",
    confidence: 0.74, langs: ["typescript"], run: smc.premiumDiscount },
  { id: "power_of_3", slug: "power_of_3", name: "Power of 3 (PO3)", category: "smc",
    short: "Accumulation + Manipulation + Distribution triad.",
    description: "ICT's daily PO3 model. 1) Accumulation: tight range. 2) Manipulation: stop-hunt wick outside range. 3) Distribution: real move in opposite direction. Also maps to Asia/London/NY session structure.",
    entry: "When manipulation completes and distribution begins.",
    exit: "SL: manipulation wick + 0.3 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.81, langs: ["typescript"], run: smc.powerOf3 },

  // ---------------- INDICATORS (12) ----------------
  { id: "triple_confluence", slug: "triple_confluence", name: "Triple Confluence", category: "indicators",
    short: "EMA + RSI + MACD triple confirmation.",
    description: "Three independent indicators pointing in the same direction. Dramatically reduces false signals. EMA50>EMA200 trend, RSI 50-70 momentum, MACD histogram positive and rising.",
    entry: "When all three conditions align.",
    exit: "SL: 2 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.8, langs: ["python", "typescript", "pinescript"], run: ind.tripleConfluence },
  { id: "bb_squeeze", slug: "bb_squeeze", name: "Bollinger Squeeze Breakout", category: "indicators",
    short: "Narrowing bands followed by volatility expansion.",
    description: "When Bollinger Bands narrow (squeeze), volatility is low; this is typically followed by an explosion. Post-squeeze break out of bands = entry.",
    entry: "Post-squeeze band breakout + volume confirmation (1.2x).",
    exit: "SL: middle band. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.75, langs: ["python", "typescript", "pinescript"], run: ind.bbSqueeze },
  { id: "ichimoku", slug: "ichimoku", name: "Ichimoku Cloud Breakout", category: "indicators",
    short: "Alignment of all Ichimoku components.",
    description: "Cloud (Kumo), Tenkan/Kijun cross and color confirmation together. Price above cloud + Tenkan>Kijun cross + green Kumo = long.",
    entry: "Price outside cloud + TK cross + Kumo color alignment.",
    exit: "SL: Kijun-sen level. TP: 1:2, 1:3, 1:5.",
    confidence: 0.8, langs: ["python", "typescript", "pinescript"], run: ind.ichimoku },
  { id: "vwap_volume", slug: "vwap_volume", name: "VWAP + Volume Profile", category: "indicators",
    short: "VWAP cross with volume spike.",
    description: "VWAP is the institutional average cost. Above = premium, below = discount. Volume spike (1.5x avg) with VWAP cross = entry.",
    entry: "VWAP cross with volume spike.",
    exit: "SL: 1.5 ATR. TP1 at Value Area level.",
    confidence: 0.72, langs: ["python", "typescript", "pinescript"], run: ind.vwapVolume },
  { id: "rsi_divergence", slug: "rsi_divergence", name: "RSI Divergence", category: "indicators",
    short: "Price-RSI mismatch signals trend weakness.",
    description: "Divergence between price and RSI indicates trend weakening. Regular bullish: price LL, RSI HL (RSI<40). Regular bearish: price HH, RSI LH (RSI>60).",
    entry: "On divergence detection.",
    exit: "SL: last swing + 0.3 ATR. TP: 1:2, 1:3, 1:5.",
    confidence: 0.78, langs: ["python", "typescript", "pinescript"], run: ind.rsiDivergence },
  { id: "chandelier", slug: "chandelier", name: "Chandelier Exit", category: "indicators",
    short: "ATR-based trailing stop system.",
    description: "ATR-based trailing stop. Highest high - ATR×3 = long stop. Trend following with dynamic stop management.",
    entry: "Price breaking chandelier level, in EMA200 direction.",
    exit: "SL: Chandelier level. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.7, langs: ["python", "typescript", "pinescript"], run: ind.chandelier },
  { id: "supertrend_adx", slug: "supertrend_adx", name: "Supertrend + ADX", category: "indicators",
    short: "Supertrend direction filtered by ADX strength.",
    description: "Supertrend gives direction, ADX filters trend strength. Signals ignored in weak trends (ADX<25).",
    entry: "Supertrend color flip + ADX>25.",
    exit: "SL: Supertrend line. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.78, langs: ["python", "typescript", "pinescript"], run: ind.supertrendAdx },
  { id: "wyckoff", slug: "wyckoff", name: "Wyckoff Phase Detection", category: "indicators",
    short: "Spring / Upthrust detection.",
    description: "Wyckoff accumulation/distribution phases. Detects Spring (false breakdown at base) and Upthrust (false breakout at top). Big moves often follow long consolidations.",
    entry: "Spring (long) or Upthrust (short) + high volume.",
    exit: "SL: wick + 0.5 ATR. TP: opposite end of range and beyond.",
    confidence: 0.82, langs: ["python", "typescript", "pinescript"], run: ind.wyckoff },
  { id: "stoch_rsi", slug: "stoch_rsi", name: "Stochastic RSI", category: "indicators",
    short: "Stochastic oscillator of RSI; extreme crosses.",
    description: "Stochastic RSI = the Stochastic formula applied to RSI. Far more sensitive than raw RSI. %K - %D crossovers at oversold (<20) or overbought (>80) zones.",
    entry: "K<20 + bullish cross or K>80 + bearish cross.",
    exit: "SL: 2 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.73, langs: ["typescript"], run: ind.stochRsi },
  { id: "donchian_breakout", slug: "donchian_breakout", name: "Donchian Channel Breakout", category: "indicators",
    short: "20-period high/low breakout (Turtle Traders classic).",
    description: "The legendary Turtle Traders 20-period high/low breakout system. Last 20 candles' high/low broken + volume confirmation. Strong momentum capture.",
    entry: "20-period upper/lower break + 1.3x volume.",
    exit: "SL: channel midpoint. TP: 1:1, 1:2, 1:3.",
    confidence: 0.71, langs: ["typescript"], run: ind.donchianBreakout },
  { id: "parabolic_sar", slug: "parabolic_sar", name: "Parabolic SAR", category: "indicators",
    short: "Trend direction with acceleration factor.",
    description: "Welles Wilder's SAR (Stop and Reverse) system. The acceleration factor (0.02-0.2) tightens the stop as the trend accelerates. Entry on trend flips.",
    entry: "SAR flip + trend confirmation.",
    exit: "SL: SAR level. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.7, langs: ["typescript"], run: ind.parabolicSar },
  { id: "keltner_squeeze", slug: "keltner_squeeze", name: "Keltner Channel Squeeze", category: "indicators",
    short: "Squeeze when BB sits inside Keltner; expansion follows.",
    description: "Logic of the TTM Squeeze indicator. When Bollinger Bands are inside the Keltner Channel, volatility is at minimum (squeeze). An expansion is expected once squeeze releases.",
    entry: "On squeeze release: outside-band breakout + volume.",
    exit: "SL: middle EMA. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.76, langs: ["typescript"], run: ind.keltnerSqueeze },

  // ---------------- MEMECOIN (9) ----------------
  { id: "volume_surge", slug: "volume_surge", name: "Volume Surge", category: "memecoin",
    short: "Sudden volume surge + positive momentum.",
    description: "Sudden surge in token volume + positive momentum. 5m volume 3x+ above average + green candle.",
    entry: "Volume ≥3x avg + green candle.",
    exit: "SL: 1.5 ATR. TP: tiered +50/+150/+300%.",
    confidence: 0.7, langs: ["python", "typescript", "pinescript"], run: meme.volumeSurge },
  { id: "tiered_exit", slug: "tiered_exit", name: "Tiered Exit", category: "memecoin",
    short: "Tiered take-profit + trailing stop system.",
    description: "Tiered take-profit matched to the pump-dump profile of memecoins. Partial exits at +50% / +150% / +300%.",
    entry: "EMA9/EMA21 cross (momentum).",
    exit: "Tiered TP: +50%, +150%, +300%. Hard SL -25%.",
    confidence: 0.7, langs: ["python", "typescript", "pinescript"], run: meme.tieredExit },
  { id: "whale_buy", slug: "whale_buy", name: "Whale Buy Detection", category: "memecoin",
    short: "Single candle with huge volume + large green body.",
    description: "Whale-buy detection: volume 5x+ average + strong green candle (body 70%+ of range) + close in upper portion (75%+). Price-based footprint of smart-money entry.",
    entry: "5x+ volume + strong green candle + upper close.",
    exit: "SL: 1.2 ATR. TP: 1:2, 1:4, 1:6.",
    confidence: 0.78, langs: ["typescript"], run: meme.whaleBuy },
  { id: "pump_cascade", slug: "pump_cascade", name: "Pump Cascade", category: "memecoin",
    short: "5+ consecutive green candles with growing momentum.",
    description: "5+ of the last 7 candles are green and candle sizes are growing. Catches the early phase of a vertical pump. High late-entry risk; tight SL + fast tiered TP.",
    entry: "5+/7 green + growing average candle size.",
    exit: "SL: 1.5 ATR (tight). TP: 1:1, 1:2, 1:3.5.",
    confidence: 0.65, langs: ["typescript"], run: meme.pumpCascade },
  { id: "bonding_curve_sniper", slug: "bonding_curve_sniper", name: "Bonding Curve Sniper", category: "memecoin",
    short: "Pump.fun bonding curve early entry.",
    description: "Catches newly launched tokens at the early stage (10-35%) of their bonding curve. 7-criterion scoring.",
    entry: "Score ≥6/7. Requires off-chain token data.",
    exit: "TP: +50/+150/+300%. SL: -30% hard stop.",
    confidence: 0.7, langs: ["python", "typescript"], run: null,
    offchainNote: "Requires on-chain token data (bonding curve %, holder count, dev wallet); cannot demo-trade with live price chart alone." },
  { id: "dev_pattern", slug: "dev_pattern", name: "Dev Pattern & First Buyers", category: "memecoin",
    short: "Developer wallet history + first-buyer analysis.",
    description: "Evaluates rug risk via the dev wallet's track record and first-buyer composition.",
    entry: "3+ green flags, no red flags. Requires off-chain data.",
    exit: "TP: 1.5x/3x/6x MC. SL: -35%.",
    confidence: 0.85, langs: ["python", "typescript"], run: null,
    offchainNote: "Requires dev wallet history, first-buyer list and bundle data." },
  { id: "holder_distribution", slug: "holder_distribution", name: "Holder Distribution", category: "memecoin",
    short: "Top-holder concentration analysis.",
    description: "Health of token holder structure. Spread = safer, concentrated = manipulation/rug risk.",
    entry: "4 of 5 criteria pass = long. Requires off-chain data.",
    exit: "TP: 1.5x/2.5x/4x MC. SL: -30%.",
    confidence: 0.75, langs: ["python", "typescript"], run: null,
    offchainNote: "Requires top-holder distribution (Birdeye/Solscan API)." },
  { id: "social_momentum", slug: "social_momentum", name: "Social Momentum", category: "memecoin",
    short: "Social media mention velocity.",
    description: "Social velocity (Twitter/Telegram/Farcaster). Mention velocity, unique posters, sentiment.",
    entry: "4 of 5 criteria pass = long. Requires off-chain data.",
    exit: "TP: 1.5x/2.5x/4x. SL: -20%.",
    confidence: 0.75, langs: ["python", "typescript"], run: null,
    offchainNote: "Requires social mention data (Neynar/LunarCrush/Twitter API)." },
  { id: "migration_play", slug: "migration_play", name: "Migration Play", category: "memecoin",
    short: "Raydium/Meteora migration event.",
    description: "Bonding curve 100% → Raydium/Meteora migration. Migration typically yields +50-200% pump.",
    entry: "Pre/post-migration conditions. Requires off-chain data.",
    exit: "Tiered TP. LP lock verification mandatory.",
    confidence: 0.78, langs: ["python", "typescript"], run: null,
    offchainNote: "Requires migration status and LP lock data." },

  // ---------------- SCALPING (3) ----------------
  { id: "quick_scalp", slug: "quick_scalp", name: "Quick Scalp RSI", category: "scalping",
    short: "Fast RSI extreme bounces (short timeframes).",
    description: "Fast scalping for 1m-5m timeframes. 7-period RSI captures extreme zones (<20 oversold long, >80 overbought short). Tight SL, fast tiered TP. High frequency, small gains.",
    entry: "RSI7 extreme + reversal candle.",
    exit: "SL: last wick + 0.2 ATR (very tight). TP: 1:1, 1:1.5, 1:2.2.",
    confidence: 0.65, langs: ["typescript"], run: scalp.quickScalp },
  { id: "range_bounce", slug: "range_bounce", name: "Range Bounce", category: "scalping",
    short: "Support/resistance bounces in tight range.",
    description: "Support/resistance bounce trading inside a tight consolidation range (last 30 candles, less than ATR×6). On reversal candle from range top/bottom, target the opposite edge.",
    entry: "Within 10% tolerance of range edge + reversal candle.",
    exit: "SL: outside range + 0.5 ATR. TP: midpoint, opposite edge.",
    confidence: 0.68, langs: ["typescript"], run: scalp.rangeBounce },
  { id: "momentum_burst", slug: "momentum_burst", name: "Momentum Burst", category: "scalping",
    short: "Single candle ATR×2+ move + volume.",
    description: "Catches sudden single-candle momentum. Body larger than 2x ATR + volume 1.5x average. Ideal for breakouts or news-driven spikes.",
    entry: "ATR×2+ candle move + volume confirmation.",
    exit: "SL: candle low/high + 0.3 ATR. TP: 1:1, 1:1.8, 1:3.",
    confidence: 0.72, langs: ["typescript"], run: scalp.momentumBurst },

  // ---------------- MEAN REVERSION (3) ----------------
  { id: "z_score_reversion", slug: "z_score_reversion", name: "Z-Score Mean Reversion", category: "meanrev",
    short: "Reversion to mean when price is 2σ away.",
    description: "Statistical mean reversion. 20-period rolling mean ± 2 standard deviations. Z-score > +2 → too high (short), Z-score < -2 → too low (long). High confidence in ranging markets, risky in trends.",
    entry: "|Z-score| > 2 + reversal candle.",
    exit: "SL: extreme wick + 0.5 ATR. TP: mean ± 0.5σ.",
    confidence: 0.7, langs: ["typescript"], run: mrev.zScoreReversion },
  { id: "rsi_extreme", slug: "rsi_extreme", name: "RSI Extreme Reversal", category: "meanrev",
    short: "RSI <20 long, >80 short — classic counter-trend.",
    description: "Classic mean-reversion use of RSI. RSI<20 + bullish reversal candle = long; RSI>80 + bearish rejection = short. Must also exceed previous candle (momentum confirmation).",
    entry: "RSI extreme + reversal candle + momentum.",
    exit: "SL: candle low/high + 0.5 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.74, langs: ["typescript"], run: mrev.rsiExtreme },
  { id: "bb_mean_reversion", slug: "bb_mean_reversion", name: "BB Mean Reversion", category: "meanrev",
    short: "Bollinger upper/lower band touch → middle band target.",
    description: "Opposite of BB squeeze breakout: band touch + reversal. Trend filter applied (BB mid slope <2%, risky in trends). Target middle band and zone between.",
    entry: "Band touch + reversal candle, in flat market.",
    exit: "SL: touch wick + 0.3 ATR. TP: middle band, 30% toward opposite band.",
    confidence: 0.7, langs: ["typescript"], run: mrev.bbMeanReversion },

  // ---------------- TREND FOLLOWING (4) ----------------
  { id: "ema_ribbon", slug: "ema_ribbon", name: "EMA Ribbon", category: "trend",
    short: "Multi-EMA (8/13/21/34/55) stacked alignment.",
    description: "Five EMAs (8, 13, 21, 34, 55) fully stacked in order = strong trend. All ascending + price above fastest EMA = long; all descending + price below = short. A fresh alignment (not aligned on prior candle) scores higher confidence than a continuation.",
    entry: "Full ribbon alignment + price beyond EMA8.",
    exit: "SL: EMA34 ± 0.5 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.78, langs: ["typescript"], run: trend.emaRibbon },
  { id: "macd_zero_cross", slug: "macd_zero_cross", name: "MACD Zero Cross", category: "trend",
    short: "MACD line crossing the zero line + EMA200 filter.",
    description: "When the MACD line crosses the zero line, momentum has flipped regime (not just a signal-line wiggle). Filtered by EMA200: bullish zero cross only taken above EMA200, bearish only below. Stronger trend confirmation than a standard MACD signal cross.",
    entry: "MACD zero-line cross in EMA200 direction.",
    exit: "SL: 2 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.74, langs: ["typescript"], run: trend.macdZeroCross },
  { id: "heikin_ashi_trend", slug: "heikin_ashi_trend", name: "Heikin Ashi Trend", category: "trend",
    short: "Heikin Ashi candle color + body-strength filter.",
    description: "Heikin Ashi smooths price to reveal trend. 3 consecutive same-color HA candles + a strong body (no opposite wick = no pullback) signals a clean trend. A flip from the opposite color scores higher confidence (early trend catch).",
    entry: "3 same-color HA candles + strong body (no counter-wick).",
    exit: "SL: 2 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.7, langs: ["typescript"], run: trend.heikinAshiTrend },
  { id: "adx_trend_rider", slug: "adx_trend_rider", name: "ADX Trend Rider", category: "trend",
    short: "ADX > 25 strength filter + DI crossover (Wilder DMI).",
    description: "Wilder's Directional Movement system. ADX measures trend strength; signals only taken when ADX > 25 (real trend present). Entry on +DI / -DI crossover: +DI crossing above -DI = long, -DI crossing above +DI = short. Filters out choppy ranges.",
    entry: "ADX > 25 + DI crossover in signal direction.",
    exit: "SL: 2 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.76, langs: ["typescript"], run: trend.adxTrendRider },

  // ---------------- BREAKOUT (4) ----------------
  { id: "opening_range_breakout", slug: "opening_range_breakout", name: "Opening Range Breakout", category: "breakout",
    short: "Break of the early-session range with volume.",
    description: "Classic ORB: define the opening range from the first 15 candles of the window, then trade a break beyond it. A break above the range high with volume = long; below the range low = short. Stop sits at the range midpoint; targets are multiples of range width.",
    entry: "Fresh close beyond opening-range high/low + 1.2x volume.",
    exit: "SL: range midpoint. TP: 1:1, 1:2, 1:3.",
    confidence: 0.72, langs: ["typescript"], run: brk.openingRangeBreakout },
  { id: "channel_breakout", slug: "channel_breakout", name: "Channel Breakout", category: "breakout",
    short: "Break of a swing-high/low price channel.",
    description: "Builds a channel from recent swing highs and lows, then trades a break of either boundary. Channel must be at least 2 ATR wide (filters noise) and the break needs 1.3x volume confirmation. Captures the start of expansion after consolidation.",
    entry: "Close beyond channel boundary + 1.3x volume.",
    exit: "SL: 1 ATR inside the broken boundary. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.73, langs: ["typescript"], run: brk.channelBreakout },
  { id: "volatility_contraction", slug: "volatility_contraction", name: "Volatility Contraction (VCP)", category: "breakout",
    short: "Minervini's tightening-range pattern before expansion.",
    description: "Mark Minervini's VCP. Three successive windows each contract to under 85% of the prior range while volume dries up — coiling energy. A close above the final contraction high on a 1.5x volume surge fires the long. One of the strongest momentum-launch setups.",
    entry: "Break above final contraction high + 1.5x volume surge.",
    exit: "SL: low of final contraction. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.77, langs: ["typescript"], run: brk.volatilityContraction },
  { id: "darvas_box", slug: "darvas_box", name: "Darvas Box", category: "breakout",
    short: "Box consolidation after a new high, break the box.",
    description: "Nicolas Darvas's box theory. After a new high, price consolidates into a box (top = the high, bottom = subsequent low). A break above the box top = long, below the bottom = short. Box must be reasonably tight (< 8 ATR) and the break needs 1.3x volume.",
    entry: "Close beyond box boundary + 1.3x volume.",
    exit: "SL: opposite box boundary. TP: 1:1, 1:2, 1:3.",
    confidence: 0.74, langs: ["typescript"], run: brk.darvasBox },

  // ---------------- CANDLESTICK PATTERNS (4) ----------------
  { id: "engulfing", slug: "engulfing", name: "Engulfing Pattern", category: "patterns",
    short: "Bullish/bearish engulfing filtered by RSI context.",
    description: "A candle whose body fully engulfs the prior opposite-color body — a sharp shift in control. Bullish engulfing taken only when RSI < 45 (oversold context), bearish only when RSI > 55. The RSI filter avoids low-quality mid-range signals.",
    entry: "Engulfing candle + RSI context confirmation.",
    exit: "SL: engulfing candle low/high + 0.3 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.73, langs: ["typescript"], run: pat.engulfing },
  { id: "pin_bar", slug: "pin_bar", name: "Pin Bar (Hammer / Star)", category: "patterns",
    short: "Long-wick rejection at support/resistance.",
    description: "A pin bar has a long wick (60%+ of range) rejecting a level with a small body. A hammer (long lower wick) near recent lows = bullish; a shooting star (long upper wick) near recent highs = bearish. The location filter (near support/resistance) is what makes it tradeable.",
    entry: "Hammer at support (long) / shooting star at resistance (short).",
    exit: "SL: wick extreme + 0.2 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.71, langs: ["typescript"], run: pat.pinBar },
  { id: "star_pattern", slug: "star_pattern", name: "Morning / Evening Star", category: "patterns",
    short: "Three-candle reversal (star in the middle).",
    description: "A three-candle reversal. Morning star: large red, then a small-body star (indecision), then a large green closing past the midpoint of candle one = bullish. Evening star is the bearish mirror. One of the most reliable classic reversal formations.",
    entry: "Completed morning/evening star formation.",
    exit: "SL: star/confirmation extreme + 0.3 ATR. TP: 1:1.5, 1:2.5, 1:4.",
    confidence: 0.76, langs: ["typescript"], run: pat.starPattern },
  { id: "three_soldiers", slug: "three_soldiers", name: "Three Soldiers / Crows", category: "patterns",
    short: "Three strong consecutive candles signal momentum.",
    description: "Three white soldiers: three consecutive strong green candles, each opening within the prior body and closing higher = sustained bullish momentum. Three black crows is the bearish mirror. Each candle needs a body of 60%+ of its range to qualify.",
    entry: "Three qualifying consecutive same-direction candles.",
    exit: "SL: first candle's extreme + 0.3 ATR. TP: 1:1, 1:1.8, 1:3.",
    confidence: 0.74, langs: ["typescript"], run: pat.threeSoldiers },
];

export function getStrategy(id: string) {
  return STRATEGIES.find((s) => s.id === id);
}

export function byCategory(cat: Category) {
  return STRATEGIES.filter((s) => s.category === cat);
}

export const CATEGORY_LABELS: Record<Category, string> = {
  smc: "SMC / Price Action",
  indicators: "Classic Indicators",
  memecoin: "Memecoin",
  scalping: "Scalping",
  meanrev: "Mean Reversion",
  trend: "Trend Following",
  breakout: "Breakout",
  patterns: "Candlestick Patterns",
};

export const ALL_CATEGORIES: Category[] = ["smc", "indicators", "memecoin", "scalping", "meanrev", "trend", "breakout", "patterns"];
